### ISSUE TITLE
当您发现后端无法连接数据库

### ISSUE THREAD

**Issue by esdeathlove** [esdeathlove/ss-panel-v3-mod#190]
像这样

![img_20160823_154558](https://cloud.githubusercontent.com/assets/7975407/17884191/7aeff734-68dc-11e6-8c79-e37c5a7cc609.jpg)

my.cnf 里 mysqld 添加如下设置

skip-name-resolve

然后重启数据库。

**Comment by sunweike** [comment]
求助啊   这个问题困扰了1天     重装最少5次系统  换了几个vps 全部这个      各种百度               设置为什么呢             作者以前没遇到过这个啊          现在怎么全是哇

**Comment by sunweike** [comment]
看到了           唉       谢谢作者大大

**Comment by sunweike** [comment]
请问下      my.cnf     在那个目录下哇           没有找到   指教下呗 谢谢哦

**Comment by sunweike** [comment]
全局检测到了       后面的人不要找了      etc目录下

**Comment by A1exLiu** [comment]
我正在尝试使用远程面板管理节点，前端和后端操作系统均为Ubuntu，已经在前端正确添加节点地址，并在后端的userapiconfig.py中设置好了节点序号，并将MYSQL_HOST改为前端所在的IP地址。但是无法使用。使用tail.sh查看日志的时候发现如下错误：
`2016-09-04 04:36:35 ERROR    auto_block.py:188 Auto block thread error
2016-09-04 04:38:43 ERROR    db_transfer.py:545 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 537, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 56, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '1**.***.***.**9' (110)")`
另外在前端所在VPS上有一个节点运行，这个节点状态正常，而远程节点无法使用，前后端互相ping没有任何问题，求解

**Comment by a86913179** [comment]
@A1exLiu 请检查防火墙，可以先关闭防火墙，具体看iptables -L，再检查数据库信息是否填写正确，ubuntu的ufw就算关闭了，iptables里还是有的。

**Comment by A1exLiu** [comment]
谢谢，不过很久之前这个issue就已经解决了😂

2016年11月12日(土) 0:35 a86913179 <notifications@github.com>:
