### ISSUE TITLE
其他节点运行后端时 显示 Can't get hostname for your address

### ISSUE THREAD

**Issue by gaoyan1234** [esdeathlove/ss-panel-v3-mod#595]
2017-01-24 22:29:10 ERROR    shell.py:50 (1042, u"Can't get hostname for your address")
2017-01-24 22:29:10 ERROR    auto_block.py:211 Auto block thread error
2017-01-24 22:29:11 ERROR    db_transfer.py:669 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 661, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 223, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 61, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 411, in _connect
    self._get_server_information()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 512, in _get_server_information
    packet = MysqlPacket(self)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/err.py", line 138, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1042, u"Can't get hostname for your address")

请问这是怎么回事

**Comment by esdeathlove** [comment]
上网搜索 Can't get hostname for your address
