### ISSUE TITLE
安装好之后，节点的测速与在线监测不工作

### ISSUE THREAD

**Issue by yoyobbs** [esdeathlove/ss-panel-v3-mod#633]
如题，不知这样的标题可以明白？期待您的解答，谢谢

**Comment by seqilove** [comment]
debug日志有么

**Comment by yoyobbs** [comment]
请问可以从哪里获取debug'日志

**Comment by yoyobbs** [comment]
$System_Config['debug'] =  'false';    您好，请问是把这里调整为TRUE吗

**Comment by zzjby** [comment]
你用的后端是什么版本。

**Comment by yoyobbs** [comment]
是您推荐的后端。
https://github.com/glzjin/shadowsocks/wiki/%E8%AF%B4%E6%98%8E%E4%BB%A5%E5%8F%8A%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

**Comment by zzjby** [comment]
我也只是用户。。。 你debug模式有信息吗。。

**Comment by yoyobbs** [comment]
还不知道从哪里找到debug信息，我自己摸索一下吧，感谢您

**Comment by gaoyuoppa** [comment]
要么是防火墙没关。要么是数据库权限没改。再或者，其他原因。不过感觉是数据库问题。

**Comment by esdeathlove** [comment]
发后端日志

**Comment by yoyobbs** [comment]
[root@localhost shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
Exception in thread autoexec:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/shadowsocks/auto_thread.py", line 33, in auto_thread
    key_data = open('ssshell.asc').read()
IOError: [Errno 2] No such file or directory: 'ssshell.asc'

2017-02-08 10:55:46 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2017-02-08 10:55:46 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('74.                                                                                        82.42.42', 53), ('4.2.2.1', 53), ('8.8.4.4', 53)]
2017-02-08 10:55:46 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('74.                                                                                        82.42.42', 53), ('4.2.2.1', 53), ('8.8.4.4', 53)]
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [1025] p                                                                                        ass [yQHptl] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:1025
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:1025
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [22841]                                                                                         pass [7Nt7mUxmWv] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:22841
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:22841
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [11058]                                                                                         pass [HVJY02] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:11058
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:11058
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [61455]                                                                                         pass [7Nt7mUxmWv] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:61455
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:61455
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [48908]                                                                                         pass [vRxiDG] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:48908
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:48908
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [27663]                                                                                         pass [f4cbI9] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:27663
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:27663
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [10382]                                                                                         pass [uEFPKI] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:10382
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:10382
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [34569]                                                                                         pass [p8VGwB] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:34569
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:34569
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [35535]                                                                                         pass [AnhI0W] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:35535
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:35535
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     db_transfer.py:646 db start server at port [50795]                                                                                         pass [gL5i2z] protocol [origin] method [rc4-md5] obfs [plain]
2017-02-08 10:55:46 INFO     server_pool.py:139 starting server at [::]:50795
2017-02-08 10:55:46 WARNING  server_pool.py:153 IPV6 [Errno 98] Address already                                                                                         in use
2017-02-08 10:55:46 INFO     server_pool.py:166 starting server at 0.0.0.0:50795
2017-02-08 10:55:46 WARNING  server_pool.py:178 IPV4 [Errno 98] Address already                                                                                         in use

**Comment by yoyobbs** [comment]
@esdeathlove 请问您说的是这个吗

**Comment by yoyobbs** [comment]
2017-02-14 10:05:27 INFO     auto_block.py:66 Read hosts.deny from line 35453
2017-02-14 10:06:27 INFO     auto_block.py:66 Read hosts.deny from line 35455
2017-02-14 10:07:27 INFO     auto_block.py:66 Read hosts.deny from line 35457
2017-02-14 10:07:49 INFO     speedtest_thread.py:25 Speedtest starting...
2017-02-14 10:08:28 INFO     auto_block.py:66 Read hosts.deny from line 35459
2017-02-14 10:09:28 INFO     auto_block.py:66 Read hosts.deny from line 35461
2017-02-14 10:10:28 INFO     auto_block.py:66 Read hosts.deny from line 35463
2017-02-14 10:10:53 INFO     speedtest_thread.py:90 Speedtest finished

------------------------------------------------------------------------
后端日志我找到了，显示测速是正常的，而且在用户界面的“观察窗”上也可以显示测速数据，数据库上也有数据，仅仅是在节点列表上的图表不显示测速数据与节点在线情况

**Comment by esdeathlove** [comment]
那就看看节点列表那里的 ajax 请求是否都正常了。

**Comment by yoyobbs** [comment]
请关闭这个贴,原因是节点的ID错了,更正后即可正常显示.谢谢
