### ISSUE TITLE
后端还不如不更新，更新问题一堆。

### ISSUE THREAD

**Issue by CxiaoyuN** [esdeathlove/ss-panel-v3-mod#690]
File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.6/site-packages/requests-2.11.1-py2.6.egg/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.11.1-py2.6.egg/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.11.1-py2.6.egg/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.11.1-py2.6.egg/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('',))

2017-02-22 17:14:28 ERROR    web_transfer.py:652 Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 641, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!
怎么搭都这样，他妈的一下午就搭个这比。所有服务器更新后出错，然后重搭就这比样，所有的一抹一摸样。还有这个2017-02-22 17:16:41 WARNING  server_pool.py:162 IPV6 [Errno 97] Address family not supported by protocol 
2017-02-22 17:16:41 INFO     server_pool.py:177 starting server at 0.0.0.0:443。完全受不了

**Comment by trumphi** [comment]
不会吧，为啥我搭建好了！找自身的原因，楼主

**Comment by ererermao** [comment]
这个问题解决了吗？
