### ISSUE TITLE
后端无法使用

### ISSUE THREAD

**Issue by moqiaoduo** [esdeathlove/ss-panel-v3-mod#691]
程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:2ad019994f14257303ccb0a70853cd62cef3dbcd

问题发生时所进行的操作：安装依赖，并运行ssr

问题所造成的影响：
安装依赖时警告：/usr/lib/python2.6/site-packages/pip-9.0.1-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

运行程序时也有错误提示（webapi连不上）：
2017-02-22 21:20:47 ERROR    webapi_utils.py:46 request nodes/4/info error!wrong ret!
2017-02-22 21:20:47 ERROR    webapi_utils.py:46 request users/aliveip error!wrong ret!
2017-02-22 21:20:47 ERROR    webapi_utils.py:46 request users/detectlog error!wrong ret!
2017-02-22 21:20:48 ERROR    webapi_utils.py:46 request func/block_ip error!wrong ret!
2017-02-22 21:20:48 ERROR    webapi_utils.py:24 request nodes/4/info error!wrong ret!
2017-02-22 21:21:43 ERROR    webapi_utils.py:24 request nodes error!wrong ret!
2017-02-22 21:21:43 INFO     auto_block.py:86 Read hosts.deny from line 31
2017-02-22 21:21:43 ERROR    webapi_utils.py:46 request func/block_ip error!wrong ret!
2017-02-22 21:21:43 ERROR    webapi_utils.py:24 request func/block_ip error!wrong ret!
2017-02-22 21:21:43 ERROR    webapi_utils.py:24 request func/unblock_ip error!wrong ret!
2017-02-22 21:21:48 INFO     connectionpool.py:249 Resetting dropped connection: xxx.com
2017-02-22 21:21:48 ERROR    webapi_utils.py:24 request func/ping error!wrong ret!
2017-02-22 21:21:48 ERROR    webapi_utils.py:46 request users/traffic error!wrong ret!
2017-02-22 21:21:48 ERROR    webapi_utils.py:46 request nodes/4/info error!wrong ret!
2017-02-22 21:21:48 ERROR    webapi_utils.py:46 request users/aliveip error!wrong ret!
2017-02-22 21:21:48 ERROR    webapi_utils.py:46 request users/detectlog error!wrong ret!
2017-02-22 21:21:49 ERROR    webapi_utils.py:46 request func/block_ip error!wrong ret!
2017-02-22 21:21:49 ERROR    webapi_utils.py:24 request nodes/4/info error!wrong ret!

其中网址已打码。
换为mysql方式，ss可用，但网页显示该节点不在线。目前尝试过3台vps（均为Centos6 x64）都是一样的结果，但也有2个vps成功安装运行（都是centos一个32bit一个64bit，python都是2.6.6）。感觉好迷，求指导！

------
补充：mysql模式下在线人数监测正常，测速貌似正常，就是不显示在线（无论前后台）。而且最后活跃时间比北京时间迟了8小时（其他用webapi的节点正常）。
------
继续补充：其他使用webapi的节点日志报错，但却正常使用：
ERROR:root:Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

ERROR:root:Traceback (most recent call last):
  File "/root/shadowsocks/auto_block.py", line 289, in thread_db
    db_instance.auto_block_thread()
  File "/root/shadowsocks/auto_block.py", line 44, in auto_block_thread
    data = webapi.getApi('nodes')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

ERROR:root:Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

ERROR:root:Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 641, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!
--------
持续追踪：貌似修复了一个数据库缺表错误后，用mysql方式已经可以显示在线，且活跃时间正常，不过Webapi仍然不可用。

**Comment by iori8421** [comment]
我日志显示正常 就是无法上网 请问需要检查哪?

**Comment by moqiaoduo** [comment]
@iori8421 检查你的防火墙设置

**Comment by esdeathlove** [comment]
1.一个issue里请只包含一个问题，有其他问题请发多个issue.
2.最后在线时间数据库模式取决于你主服务器的时间设置。
3. web api 请检查节点列表里是否有这个节点，并且节点 IP 处是否正确读出。

**Comment by moqiaoduo** [comment]
@esdeathlove 感谢，已经解决，确实是节点IP的问题，现在已经正常使用web api

**Comment by setsunawang** [comment]
@moqiaoduo 请问你是怎么解决的呢，我检查节点列表前后端ID正确，前端能正确显示节点IP，依然和你一样的报错

**Comment by moqiaoduo** [comment]
@setsunawang 看看防火墙关了没

**Comment by mischief1** [comment]
@moqiaoduo  怎么解决的呢 web api 请检查节点列表里是否有这个节点? 能详细点吗 我也是同样的问题

**Comment by moqiaoduo** [comment]
@mischief1 你要事先在前端添加节点，然后把节点id填入后端的node_id处

**Comment by mischief1** [comment]
@moqiaoduo 我也改成数据库模式了？你知道webapi模式怎么配置吗 谢谢

**Comment by moqiaoduo** [comment]
@mischief1 后端设置是这样的：
NODE_ID =  //设置为节点id

API_INTERFACE = 'modwebapi' //设置为这个

WEBAPI_URL = ''  //设置为网址，要带http或https
WEBAPI_TOKEN = ''  //设置为在前端设置的muKey

至于前端muKey，当然是在.config.php

**Comment by mischief1** [comment]
@moqiaoduo 感谢很详细 没有错误 就只有warning 也能正常运行了

另外我想问下邮件配置

$System_Config['smtp_host'] = 'smtp.126.com';
$System_Config['smtp_username'] = '邮箱地址';
$System_Config['smtp_port'] = '25';
$System_Config['smtp_name'] = '邮箱地址';
$System_Config['smtp_sender'] = '邮箱地址';
$System_Config['smtp_passsword'] = '密码';
$System_Config['smtp_ssl'] = 'false';

这么对不对呀  126邮箱smtp服务已开，可是还是无法发送邮件，还需要改哪里，或者是哪里错误吗

**Comment by moqiaoduo** [comment]
@mischief1 我记得126邮箱的smtp认证密码是授权码，还有smtp_name填发件人名称（如站名）就可以了，如果这些都没有问题，你可以试试其他的一些邮箱如gmail，如果不行的话可能是相关端口被封或者你的系统缺少一些发件组件。

**Comment by mischief1** [comment]
@moqiaoduo  用的是vultr 还要设置哪里吗 QQ 126都试过了

**Comment by mischief1** [comment]
@moqiaoduo  已解决，smtp.php默认端口587  需要修改 或者改用谷歌邮箱 用SLL连接  谢谢

我还想问下，节点列表有个小三角，怎么解决

**Comment by mischief1** [comment]
已解决，我用的单端口多用户模式，节点ID要设置成原来的ID

**Comment by tang1989324** [comment]
@moqiaoduo 默认muKey是空白的 要设置吗？

**Comment by 693098385** [comment]
一样的问题路过。。。glzjinmod全部正常。。。modwebapi就Exception: network issue or server error!

**Comment by ererermao** [comment]
@moqiaoduo 我也是 modwebapi就Exception: network issue or server error!。数据库模式怎么配置的。能不能大致讲一下。谢谢
