### ISSUE TITLE
17年2月20日号版本更新后报错

### ISSUE THREAD

**Issue by Huanhoo** [esdeathlove/ss-panel-v3-mod#693]
程序类型：前端

程序版本:2017年2月20日号版本

问题发生时所进行的操作：22号下午git pull后，管理员登录后进入后台，点开“节点列表”，“商品列表”，弹出错误弹窗

![issue1](https://cloud.githubusercontent.com/assets/3039189/23243565/b3a55b18-f9ba-11e6-8fa5-bc1f45bbe2f6.png)

问题所造成的影响：管理后台除用户列表和系统概览外，其余均弹出错误弹窗。

调试日志（按照上面的调试方法得到）：
浏览器返回：
{
    "message": "Slim Application Error",
    "error": [
        {
            "type": "Error",
            "code": 0,
            "message": "Class 'Ozdemir\\Datatables\\Datatables' not found",
            "file": "\/home\/wwwroot\/ss.panel\/app\/Controllers\/Admin\/ShopController.php",
            "line": 186,
            "trace": [
                "#0 [internal function]: App\\Controllers\\Admin\\ShopController->ajax_shop(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#1 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#2 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/Route.php(344): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#3 \/home\/wwwroot\/ss.panel\/app\/Middleware\/Admin.php(26): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#4 [internal function]: App\\Middleware\\Admin->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#5 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/DeferredCallable.php(43): call_user_func_array(Object(App\\Middleware\\Admin), Array)",
                "#6 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#7 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#8 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(116): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#9 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/Route.php(316): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#10 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/App.php(438): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#11 \/home\/wwwroot\/ss.panel\/vendor\/zeuxisoo\/slim-whoops\/src\/Zeuxisoo\/Whoops\/Provider\/Slim\/WhoopsMiddleware.php(62): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#12 [internal function]: Zeuxisoo\\Whoops\\Provider\\Slim\\WhoopsMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))",
                "#13 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/DeferredCallable.php(43): call_user_func_array(Object(Zeuxisoo\\Whoops\\Provider\\Slim\\WhoopsMiddleware), Array)",
                "#14 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))",
                "#15 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))",
                "#16 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(116): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#17 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/App.php(332): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#18 \/home\/wwwroot\/ss.panel\/vendor\/slim\/slim\/Slim\/App.php(293): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#19 \/home\/wwwroot\/ss.panel\/config\/routes.php(340): Slim\\App->run()",
                "#20 \/home\/wwwroot\/ss.panel\/public\/index.php(11): require('\/home\/wwwroot\/s...')",
                "#21 {main}"
            ]
        }
    ]
}

感谢解答！

**Comment by Huanhoo** [comment]
抱歉，恕我眼拙，没看到“php composer.phar install”这句话，执行完毕后已经好了，打扰了，十分感谢！
