### ISSUE TITLE
请问后端modwebapi方式工作不稳定是什么原因？（已附上log）

### ISSUE THREAD

**Issue by jack338c** [esdeathlove/ss-panel-v3-mod#711]
时好时坏不稳定

017-03-02 21:02:58 ERROR    tcprelay.py:1400 [Errno 104] Connection reset by peer
2017-03-02 21:02:58 ERROR    tcprelay.py:1408 when connect to by3301.storage.live.com:443 from ::ffff:111.140.58.220:13832 via port 443
2017-03-02 21:03:05 INFO     connectionpool.py:249 Resetting dropped connection: xxxx.com
2017-03-02 21:03:05 INFO     auto_block.py:86 Read hosts.deny from line 1281
2017-03-02 21:03:21 INFO     connectionpool.py:214 Starting new HTTP connection (9): xxxx.com
2017-03-02 21:04:06 INFO     connectionpool.py:249 Resetting dropped connection: xxxx.com
2017-03-02 21:04:06 INFO     auto_block.py:86 Read hosts.deny from line 1283
2017-03-02 21:04:23 ERROR    webapi_utils.py:30 Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

2017-03-02 21:04:23 ERROR    web_transfer.py:652 Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 641, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

2017-03-02 21:05:06 INFO     auto_block.py:86 Read hosts.deny from line 1285
2017-03-02 21:05:23 INFO     connectionpool.py:214 Starting new HTTP connection (10): xxxx.com
2017-03-02 21:06:06 INFO     auto_block.py:86 Read hosts.deny from line 1287
2017-03-02 21:06:24 INFO     connectionpool.py:249 Resetting dropped connection: xxxx.com
2017-03-02 21:07:07 INFO     auto_block.py:86 Read hosts.deny from line 1289
2017-03-02 21:07:26 INFO     connectionpool.py:249 Resetting dropped connection: xxxx.com
2017-03-02 21:07:41 INFO     tcprelay.py:1732 port 443 connections up to 50
2017-03-02 21:08:07 INFO     auto_block.py:86 Read hosts.deny from line 1291
2017-03-02 21:08:27 INFO     connectionpool.py:249 Resetting dropped connection: xxxx.com
2017-03-02 21:09:05 INFO     tcprelay.py:1735 port 443 connections down to 25
2017-03-02 21:09:07 INFO     auto_block.py:86 Read hosts.deny from line 1293
2017-03-02 21:09:28 INFO     connectionpool.py:249 Resetting dropped connection: xxxx.com
2017-03-02 21:10:29 INFO     auto_block.py:86 Read hosts.deny from line 1295
2017-03-02 21:10:29 INFO     util.py:85 loading libcrypto from libcrypto.so.10

**Comment by moqiaoduo** [comment]
1.检查使用的是否为Https协议
2.挂个监控看看你的网站是否稳定，当然也可以在服务器里面ping
3.看看你的域名是否做了301重定向

如果检查以上无法解决，请自己摸索或者等待作者回复

**Comment by jack338c** [comment]
好的，多谢提示!

**Comment by silentstage** [comment]
我和你同样的问题，同样的设置在以前的ssr节点就完全没事，复制以前SSR到新节点也没事，但是按wiki教程重新部署就会出错。

**Comment by jack338c** [comment]
@silentstage 你也可以贴出LOGO来，让热心朋友帮你分析下
