### ISSUE TITLE
关于后端经常掉线再恢复的问题

### ISSUE THREAD

**Issue by Awelling2** [esdeathlove/ss-panel-v3-mod#756]
程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:1670f9312efa8b6f1a8d97faeae9c2781d680458

问题发生时所进行的操作：仅重启过数据库跟前端

问题所造成的影响：前端面板的部分节点为红色，但是节点可以连接，经常掉线再恢复，开新机对接也是这个样子。curl过为pong,尝试过使用数据库模式连接，把nginx 的周期调成75，无果，所以只能求助

`调试日志（按照上面的调试方法得到）：2017-03-31 00:36:52 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-03-31 00:37:26 INFO     auto_block.py:88 Read hosts.deny from line 33
2017-03-31 00:37:43 ERROR    db_transfer.py:863 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 855, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 286, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 108, in update_all_user
    "', unix_timestamp()); ")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (145, u"Table './sspanel/user_traffic_log' is marked as crashed and should be repaired")

2017-03-31 00:38:28 INFO     auto_block.py:88 Read hosts.deny from line 35
2017-03-31 00:38:44 ERROR    db_transfer.py:863 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 855, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 286, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 108, in update_all_user
    "', unix_timestamp()); ")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (145, u"Table './sspanel/user_traffic_log' is marked as crashed and should be repaired")

2017-03-31 00:39:12 INFO     speedtest_thread.py:23 Speedtest starting...You can't stop right now!
2017-03-31 00:39:29 INFO     auto_block.py:88 Read hosts.deny from line 37
2017-03-31 00:39:45 ERROR    db_transfer.py:863 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 855, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 286, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 108, in update_all_user
    "', unix_timestamp()); ")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (145, u"Table './sspanel/user_traffic_log' is marked as crashed and should be repaired")

2017-03-31 00:40:31 INFO     auto_block.py:88 Read hosts.deny from line 39
2017-03-31 00:40:32 INFO     speedtest_thread.py:155 Speedtest finished
2017-03-31 00:40:47 ERROR    db_transfer.py:863 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 855, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 286, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 108, in update_all_user
    "', unix_timestamp()); ")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (145, u"Table './sspanel/user_traffic_log' is marked as crashed and should be repaired")

`

**Comment by Awelling2** [comment]
已解决
数据库表user_traffic_log出错，清空即可
