### ISSUE TITLE
后端 No module named 'resource'

### ISSUE THREAD

**Issue by backrunner** [esdeathlove/ss-panel-v3-mod#759]
程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）: 1ee3442

问题发生时所进行的操作：python server.py

问题所造成的影响：我不能在windows上跑后端

调试日志（按照上面的调试方法得到）：
loaded collections.OrderedDict
IPv6 support
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\shadowsocks\server.py", line 48, in run
    self.obj.thread_db(self.obj)
  File "C:\shadowsocks\db_transfer.py", line 846, in thread_db
    import resource
ModuleNotFoundError: No module named 'resource'

还有一个module是fnctl也是类似

环境：AWS EC2+Windows server 2016+python 3.6.1

**Comment by esdeathlove** [comment]
不要在Windows下使用。
