### ISSUE TITLE
后端无法连接前端但curl api正常

### ISSUE THREAD

**Issue by backrunner** [esdeathlove/ss-panel-v3-mod#770]
程序类型（前端/后端）：后端
程序版本（前端发版本号，后端发 git log 所看到的 commit id）:最新
问题发生时所进行的操作：python server.py

loaded collections.OrderedDict
IPv6 not support
ERROR:root:Traceback (most recent call last):
  File "/home/shadowsocks/webapi_utils.py", line 44, in postApi
    timeout=10).json()
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'

ERROR:root:Traceback (most recent call last):
  File "/home/shadowsocks/auto_block.py", line 291, in thread_db
    db_instance.auto_block_thread()
  File "/home/shadowsocks/auto_block.py", line 166, in auto_block_thread    'func/block_ip', {'node_id': configloader.get_config().NODE_ID}, {'data': data})
  File "/home/shadowsocks/webapi_utils.py", line 53, in postApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

2017-04-09 01:55:48 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-04-09 01:55:48 INFO     asyncdns.py:330 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-04-09 01:55:48 INFO     asyncdns.py:330 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-04-09 01:55:48 ERROR    webapi_utils.py:52 Traceback (most recent call last):
  File "/home/shadowsocks/webapi_utils.py", line 44, in postApi
    timeout=10).json()
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'

2017-04-09 01:55:48 ERROR    web_transfer.py:653 Traceback (most recent call last):
  File "/home/shadowsocks/web_transfer.py", line 647, in thread_db
    db_instance.push_db_all_user()
  File "/home/shadowsocks/web_transfer.py", line 199, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/home/shadowsocks/web_transfer.py", line 61, in update_all_user
    {'data': data})
  File "/home/shadowsocks/webapi_utils.py", line 53, in postApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

root@iZt4nh8nr0sr6yrm5dlm4xZ:/home/shadowsocks# curl http://ss.backrunner.top/mod_mu/nodes?key=backrunner
{"ret":1,"data":[{"id":5,"name":"AWS-KOR-SSR","type":1,"server":"52.79.224.73","method":"aes-256-cfb","info":"SSR","status":"OK","sort":0,"custom_method":1,"traffic_rate":1,"node_class":2,"node_speedlimit":0,"node_connector":0,"node_bandwidth":0,"node_bandwidth_limit":0,"bandwidthlimit_resetday":1,"node_heartbeat":1491674290,"node_ip":"52.79.224.73","node_group":0,"custom_rss":1,"mu_only":0},{"id":6,"name":"ALIYUN-SG-SSR","type":1,"server":"47.88.225.253","method":"AES-256-CFB","info":"ALIYUN-SG, 1CPU, 1G RAM, 40G HDD, 30Mbps","status":"Installing","sort":0,"custom_method":1,"traffic_rate":1,"node_class":0,"node_speedlimit":0,"node_connector":0,"node_bandwidth":0,"node_bandwidth_limit":"2199023255552","bandwidthlimit_resetday":9,"node_heartbeat":0,"node_ip":"47.88.225.253","node_group":0,"custom_rss":1,"mu_only":0}]}

为什么会出现这样的错误
有另一台aws完全正常，配置文件也检查了多次了没有问题，依赖也都挨个装好了。

**Comment by backrunner** [comment]
已解决..
阿里云自带了低版本requests，删掉系统的就行了
