### ISSUE TITLE
前端与后端的连接有问题 1045错误

### ISSUE THREAD

**Issue by binlixmax** [esdeathlove/ss-panel-v3-mod#782]
程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:0fb55fc8ec67ecff2af3b5fdcee16a017b8d123c

问题发生时所进行的操作：./tail.sh

问题所造成的影响：前端与后端的连接有问题，前端与后端没法连接。Ps.理论上来说，根据日志显示的最后一句话，可以得出，是数据库的连接被拒绝，但是我可以确定当前使用的数据库的信息是没有问题的，应该，因为前端可以正常添加账户，且我能在user表中查看到信息。感谢大大的帮助。

调试日志（按照上面的调试方法得到）：
2017-04-15 22:05:20 ERROR    db_transfer.py:863 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 855, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 286, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 77, in update_all_user
    charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 135, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
OperationalError: (1045, u"Access denied for user 'sspanel'@'127.0.0.1' (using password: YES)")

**Comment by roddyofchina** [comment]
连接不上数据库，或者没有权限

**Comment by esdeathlove** [comment]
数据库帐号用户名或密码错误。

**Comment by 40huo** [comment]
你需要新建一个host为127.0.0.1的数据库账户。
