### ISSUE TITLE
节点能用，但是总是会出现类似ERROR    webapi_utils.py:30 Traceback (most recent call last):的错误

### ISSUE THREAD

**Issue by jack338c** [esdeathlove/ss-panel-v3-mod#794]
程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:
commit e6b2bda65e82a33b149e9e8c7e805d5e9f868c9c
Author: 破娃酱 <mmgac001@gmail.com>
Date:   Sat Apr 8 22:02:35 2017 +0800

问题发生时所进行的操作：cat /root/shadowsocks/ssserver.log

问题所造成的影响：暂时没有，但担心会有问题

调试日志（按照上面的调试方法得到）：
节点能使用，但是不知道为什么还是会出现这样的错误
前后端requests= 2.13.0

2017-04-24 20:44:37 ERROR    tcprelay.py:1432 [Errno 104] Connection reset by peer
2017-04-24 20:44:37 ERROR    tcprelay.py:1436 exception from ::ffff:111.140.58.194:30141
2017-04-24 20:44:37 ERROR    tcprelay.py:1432 [Errno 104] Connection reset by peer
2017-04-24 20:44:37 ERROR    tcprelay.py:1436 exception from ::ffff:111.140.58.194:30063
2017-04-24 20:44:38 INFO     auto_block.py:88 Read hosts.deny from line 12651
2017-04-24 20:44:46 ERROR    tcprelay.py:1432 [Errno 104] Connection reset by peer
2017-04-24 20:44:46 ERROR    tcprelay.py:1436 exception from ::ffff:111.140.58.194:29886
2017-04-24 20:44:46 ERROR    tcprelay.py:1432 [Errno 104] Connection reset by peer
2017-04-24 20:44:46 ERROR    tcprelay.py:1436 exception from ::ffff:111.140.58.194:30296
2017-04-24 20:45:01 ERROR    tcprelay.py:1432 [Errno 104] Connection reset by peer
2017-04-24 20:45:01 ERROR    tcprelay.py:1436 exception from ::ffff:111.140.58.194:30014
2017-04-24 20:45:09 ERROR    tcprelay.py:1432 [Errno 104] Connection reset by peer
2017-04-24 20:45:09 ERROR    tcprelay.py:1436 exception from ::ffff:111.140.58.194:30274
2017-04-24 20:45:34 ERROR    tcprelay.py:1432 [Errno 104] Connection reset by peer
2017-04-24 20:45:34 ERROR    tcprelay.py:1436 exception from ::ffff:111.140.58.194:30180
2017-04-24 20:45:39 INFO     auto_block.py:88 Read hosts.deny from line 12653
2017-04-24 20:45:55 ERROR    webapi_utils.py:30 Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

2017-04-24 20:45:55 ERROR    web_transfer.py:653 Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 642, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

请帮忙看一看，感谢!

**Comment by leoleoasd** [comment]
正常

**Comment by esdeathlove** [comment]
请设置 nginx的keepalive timeout

**Comment by jack338c** [comment]
@esdeathlove 
老大，谢谢你回复我，我的问题是想用安全连接方式，按照https://github.com/esdeathlove/shadowsocks/wiki/Mysql-SSL-%E9%85%8D%E7%BD%AE
的说明，证书都生成了，用的是lnmp一键包，mysql版本5.6.29参照https://www.digitalocean.com/community/tutorials/how-to-configure-ssl-tls-for-mysql-on-ubuntu-16-04
能下面一样的了,但是\s后显示not in use,
请帮帮我，没有你实在搞不定


| Variable_name | Value           |
+---------------+-----------------+
| have_openssl  | YES             |
| have_ssl      | YES             |
| ssl_ca        | ca.pem          |
| ssl_capath    |                 |
| ssl_cert      | server-cert.pem |
| ssl_cipher    |                 |
| ssl_crl       |                 |
| ssl_crlpath   |                 |
| ssl_key       | server-key.pem





﻿# Config
NODE_ID = 2


# hour,set 0 to disable
SPEEDTEST = 6
CLOUDSAFE = 1
ANTISSATTACK = 0
AUTOEXEC = 0

MU_SUFFIX = 'zhaoj.in'
MU_REGEX = '%5m%id.%suffix'

SERVER_PUB_ADDR = '127.0.0.1'  # mujson_mgr need this to generate ssr link
API_INTERFACE = 'modwebapi'  # glzjinmod, modwebapi（**发这段内容前改成glzjinmod，出现下面的错误，最后的LOG就是)**

WEBAPI_URL = 'http://xxxx'
WEBAPI_TOKEN = '9988776655'

# mudb
MUDB_FILE = 'mudb.json'

# Mysql
MYSQL_HOST = '192.xxxxxxx'
MYSQL_PORT = 3306
MYSQL_USER = 'sspanxxel'
MYSQL_PASS = 's4xylb4xxx88'
MYSQL_DB = 'sspanel'

MYSQL_SSL_ENABLE = 1
MYSQL_SSL_CA = '/root/shadowsocks/ca.pem'
MYSQL_SSL_CERT = '/root/shadowsocks/client-cert.pem'
MYSQL_SSL_KEY = '/root/shadowsocks/client-key.pem'

# API
API_HOST = '127.0.0.1'
API_PORT = 80
API_PATH = '/mu/v2/'
API_TOKEN = '9988776655'
API_UPDATE_TIME = 60

# Manager (ignore this)
MANAGE_PASS = 'ss233333333'
# if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
# make sure this port is idle
MANAGE_PORT = 23333

# Safety
IP_MD5_SALT = 'randomforsafety'




2017-04-25 16:08:58 ERROR    db_transfer.py:863 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 855, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 286, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 69, in update_all_user
    'key': get_config().MYSQL_SSL_KEY})
  File "/usr/lib/python2.7/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 472, in _send_authentication
    ca_certs=self.ca)
  File "/usr/lib64/python2.7/ssl.py", line 936, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 833, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

**Comment by esdeathlove** [comment]
你要真改API_INTERFACE然后重启，不会有那个提示的。

**Comment by jack338c** [comment]
@esdeathlove 
是的，我改了后现在是这样的错误

2017-04-25 18:59:31 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-04-25 18:59:31 INFO     asyncdns.py:330 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-04-25 18:59:31 INFO     asyncdns.py:330 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-04-25 18:59:31 INFO     auto_block.py:88 Read hosts.deny from line 153731
2017-04-25 18:59:31 ERROR    db_transfer.py:863 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 857, in thread_db
    db_instance.del_server_out_of_bound_safe(last_rows, rows)
  File "/root/shadowsocks/db_transfer.py", line 618, in del_server_out_of_bound_safe
    cfg['ip_md5_salt'] = get_config().IP_MD5_SALT
AttributeError: 'module' object has no attribute 'IP_MD5_SALT'

**Comment by jack338c** [comment]
我基本搞定了，就差一个节点出问题了
再次感谢esdeathlove，好人一生平安
