### ISSUE TITLE
后端与数据库连接失败

### ISSUE THREAD

**Issue by EasonSummer** [esdeathlove/ss-panel-v3-mod#821]
#程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:faa78b5cc21bfea4348bdc6c2b7c385c305946b9

问题发生时所进行的操作：python server.py -d start

问题所造成的影响：后端用非ssl方式连接mysql是成功的，但是一旦切换到ssl方式就链接不上mysql。直接mysql client用ssl方式，能顺利链接到数据库。请问大大问题出来哪里呢？

mysql直接连接的情况：
root@sserver2:mysql -u 5556 -p --ssl-ca=/etc/mysql/ca-cert.pem --ssl-cert=/etc/mysql/client-cert.pem    --ssl-key=/etc/mysql/client-key.pem -h 123.0.0.0
 Enter password:
 Welcome to the MySQL monitor.  Commands end with ; or \g.
 Your MySQL connection id is 1016
 Server version: 5.5.50-log Source distribution

  Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

 Oracle is a registered trademark of Oracle Corporation and/or its
 affiliates. Other names may be trademarks of their respective
 owners.

 Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

   mysql> status

   mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper

Connection id:          1016
Current database:
Current user:           sss@124.0.0.0
SSL:                    Cipher in use is DHE-RSA-AES256-SHA
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         5.5.50-log Source distribution
Protocol version:       10
Connection:             123.0.0.0 via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8
Conn.  characterset:    utf8
TCP port:               3306
Uptime:                 4 hours 4 min 34 sec

   Threads: 1  Questions: 10646  Slow queries: 0  Opens: 48  Flush tables: 1  Open tables: 41  Queries per              second avg: 0.725

  mysql>

配置文件如下：
 #Mysql
MYSQL_HOST = 'XXXXXXX''
MYSQL_PORT = 3306
MYSQL_USER = 'XX'
MYSQL_PASS = 'XXXXXXXX'
MYSQL_DB = 'XXX'

MYSQL_SSL_ENABLE = 1
MYSQL_SSL_CA = '/etc/mysql/ca-cert.pem'
MYSQL_SSL_CERT = '/etc/mysql/client-cert.pem'
MYSQL_SSL_KEY = '/etc/mysql/client-key.pem'

调试日志（按照上面的调试方法得到）：
2017-05-17 15:05:31 ERROR    auto_block.py:292 Traceback (most recent call last)                            :
  File "/etc/shadowsocks/auto_block.py", line 288, in thread_db
    db_instance.auto_block_thread()
  File "/etc/shadowsocks/auto_block.py", line 61, in auto_block_thread
    'key': configloader.get_config().MYSQL_SSL_KEY})
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in                             Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244                            , in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 412                            , in _connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 443                            , in _request_authentication
    self._send_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 472                            , in _send_authentication
    ca_certs=self.ca)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: _ssl.c:489: The handshake operation timed out

2017-05-17 15:05:31 ERROR    db_transfer.py:870 Traceback (most recent call last                            ):
  File "/etc/shadowsocks/db_transfer.py", line 862, in thread_db
    db_instance.push_db_all_user()
  File "/etc/shadowsocks/db_transfer.py", line 286, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/etc/shadowsocks/db_transfer.py", line 69, in update_all_user
    'key': get_config().MYSQL_SSL_KEY})
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in                             Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244                            , in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 412                            , in _connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 443                            , in _request_authentication
    self._send_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 472                            , in _send_authentication
    ca_certs=self.ca)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: _ssl.c:489: The handshake operation timed out

**Comment by moqiaoduo** [comment]
尝试关闭mysql ssl连接，如果成功连接说明是ssl问题，因为错误日志提示握手失败

**Comment by EasonSummer** [comment]
谢谢你解答。关闭ssl是能成功连接，但是mysql client是握手成功的。好奇怪

**Comment by esdeathlove** [comment]
操作超时，检查一下网络连线状况吧。
