### ISSUE TITLE
shadowsocks服务启动有问题

### ISSUE THREAD

**Issue by ererermao** [esdeathlove/ss-panel-v3-mod#823]
### 程序类型（前端/后端）：
后端

### 程序版本（前端发版本号，后端发 git log 所看到的 commit id）:
ShadowsocksR 3.3.0 2017-05-11 mod by esdeathlove

### 问题发生时所进行的操作：
运行`python server.py `

### 问题所造成的影响：
客户端无法连接到ShadowsocksR服务

### 配置时参考文档
[点击查看：https://github.com/esdeathlove/shadowsocks/wiki/%E9%87%8D%E5%A4%A7%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#20170215](https://github.com/esdeathlove/shadowsocks/wiki/%E9%87%8D%E5%A4%A7%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#20170215)

### 调试日志（按照上面的调试方法得到）：
```
ERROR: Traceback (most recent call last):
  File "/home/ss/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
### 自己思考的结论
- 是由于HTTP API配置有问题，但是不知道哪里有错。数据库方式也不能用
- [密钥在一台机器可以，另外一台又不可以，见下图
![image](http://og20qmy78.bkt.clouddn.com/github/image/QQ%E6%88%AA%E5%9B%BE20170519211732.png)

谢谢配合！

**Comment by ererermao** [comment]
换成root用户好了，具体什么原因。以后有时间在好好验证下。
