### ISSUE TITLE
节点可正常运作，但是在清单上总是出现红色惊叹号

### ISSUE THREAD

**Issue by wulin00f** [esdeathlove/ss-panel-v3-mod#852]
程序类型（前端/后端）：前端
程序版本：都为最新
问题发生时所进行的操作：刚装好时还是正常，现在就出现红色惊叹号，重启没用
问题所造成的影响：清单上总是出现红色惊叹号

后端有两台都发生同样情况；后端Node ID已经与前端网页上的匹配
WEBAPI_URL，muKey，node_id

请问要从哪个方向去查问题，谢谢~

以下是ssserver.log:

  File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

2017-06-03 16:41:18 ERROR    web_transfer.py:672 Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 660, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

2017-06-03 16:42:12 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-06-03 16:43:13 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-06-03 16:43:20 ERROR    webapi_utils.py:30 Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

2017-06-03 16:43:20 ERROR    web_transfer.py:672 Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 660, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

**Comment by moqiaoduo** [comment]
建议打开前端debug，然后一个接一个检查页面

**Comment by moqiaoduo** [comment]
比较正式的方法是：改为数据库方式对接，然后查看有无错误日志，尤其要注意数据库表方面的报错；如果没有，尝试重装ssr后端。

**Comment by wulin00f** [comment]
问题解决了~~谢谢！

原来问题出在前端..
