### ISSUE TITLE
后端配置完成后无法连接到节点。

### ISSUE THREAD

**Issue by KiyoshiKwok** [esdeathlove/ss-panel-v3-mod#860]
程序类型（前端/后端）：后端

程序版本（前端发版本号，后端发 git log 所看到的 commit id）:均为最新

问题发生时所进行的操作：python server.py

问题所造成的影响：无法连接到节点

调试日志（按照上面的调试方法得到）：2017-06-09 16:41:14 ERROR    webapi_utils.py:30 Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 22, in getApi
    timeout=10).json()
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='kiyoshiss.info', port=443): Max retries exceeded with url: /mod_mu/func/ping?key=wo94tyzxxm (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f45e4035950>: Failed to establish a new connection: [Errno -2] Name or service not known',))

2017-06-09 16:41:14 ERROR    web_transfer.py:672 Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 660, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 31, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

**Comment by yiyeluo** [comment]
请问这个问题解决了吗？我今天添加节点，也有这个问题。

**Comment by esdeathlove** [comment]
修改服务器DNS。
