### ISSUE TITLE
节点状态显示异常

### ISSUE THREAD

**Issue by koyomisan** [esdeathlove/ss-panel-v3-mod#883]
程序类型：前端

程序版本:前端为最新，后端为b669960328187dfafb74a9c272a07ec8ef1e3d20

问题发生时所进行的操作：添加节点

问题所造成的影响：所添加的节点可用但是状态始终显示为黄色感叹号，观察窗内无测速信息

调试日志（后端）：
INFO: ShadowsocksR 3.3.3.2 2017-06-03 mod by esdeathlove
INFO: current process RLIMIT_NOFILE resource: soft 512000 hard 512000
INFO: loading config from user-config.json
2017-07-13 17:13:48 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2017-07-13 17:13:48 INFO     asyncdns.py:324 dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]
2017-07-13 17:13:48 INFO     asyncdns.py:324 dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]
2017-07-13 17:13:48 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:13:49 INFO     db_transfer.py:820 db start server at port [1025] pass [FLrmm7] protocol [origin] method [aes-256-cfb] obfs [plain]
2017-07-13 17:13:49 INFO     server_pool.py:147 starting server at [::]:1025
2017-07-13 17:13:49 INFO     server_pool.py:177 starting server at 0.0.0.0:1025
2017-07-13 17:13:49 INFO     db_transfer.py:820 db start server at port [33848] pass [O5Grrx] protocol [origin] method [aes-256-cfb] obfs [plain]
2017-07-13 17:13:49 INFO     server_pool.py:147 starting server at [::]:33848
2017-07-13 17:13:49 INFO     server_pool.py:177 starting server at 0.0.0.0:33848
2017-07-13 17:14:48 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:15:49 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:16:49 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:17:49 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:18:49 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:19:49 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:20:49 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:21:49 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:22:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:23:48 INFO     speedtest_thread.py:23 Speedtest starting...You can't stop right now!
2017-07-13 17:23:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:24:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:25:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:26:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:27:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:28:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:29:50 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:30:51 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:31:51 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:32:51 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:33:51 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:34:51 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:35:51 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:36:26 INFO     speedtest_thread.py:155 Speedtest finished
2017-07-13 17:36:51 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:37:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:38:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:39:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:40:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:41:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:42:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:43:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:44:52 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:45:53 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:46:53 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:47:53 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:48:53 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:49:53 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:50:53 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:51:53 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:52:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:53:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:54:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:55:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:56:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:57:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:58:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 17:59:54 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:00:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:01:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:02:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:03:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:04:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:05:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:06:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:07:55 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:08:56 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:09:56 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:10:56 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:11:56 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:12:56 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:13:56 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:14:56 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:15:57 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:16:57 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:17:57 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:18:57 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:19:57 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:20:57 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:21:57 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:22:58 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:23:58 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:24:58 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:25:58 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:26:58 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:27:58 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:28:58 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:29:59 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:30:59 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:31:59 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:32:59 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:33:59 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:34:59 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:35:59 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:37:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:38:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:39:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:40:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:41:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:42:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:43:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:44:00 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:45:01 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:46:01 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:47:01 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:48:01 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:49:01 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:50:01 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:51:01 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:52:02 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:53:02 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:54:02 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:55:02 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:56:02 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:57:02 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:58:02 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 18:59:03 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:00:03 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:01:03 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:02:03 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:03:03 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:04:03 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:05:03 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:06:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:07:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:08:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:09:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:10:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:11:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:12:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:13:04 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:14:05 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:15:05 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:16:05 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:17:05 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:18:05 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:19:05 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:20:05 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:21:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:22:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:23:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:24:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:25:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:26:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:27:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:28:06 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:29:07 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:30:07 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:31:07 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:32:07 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:33:07 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:34:07 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:35:07 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:36:08 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:37:08 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:38:08 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:39:08 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:40:08 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:41:08 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:42:08 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:43:09 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:44:09 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:45:09 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:46:09 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:47:09 INFO     auto_block.py:88 Read hosts.deny from line 13
2017-07-13 19:48:12 ERROR    auto_block.py:292 Traceback (most recent call last):
  File "/root/libsodium-1.0.10/shadowsocks/auto_block.py", line 288, in thread_db
    db_instance.auto_block_thread()
  File "/root/libsodium-1.0.10/shadowsocks/auto_block.py", line 69, in auto_block_thread
    charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '107.174.206.X' (111)")
然后无限重复

前后端时间一致，前端已开放3306端口，后端防火墙已关闭

**Comment by MicrosoftYK** [comment]
1.查看该用户是否有远程登录的权限；
2.查看 MySQL Server 是不是监听了 3306 端口；
3.如果服务器是 CentOS7，将 MySQL 服务加入防火墙；
可以参考：http://blog.csdn.net/showhilllee/article/details/53010617
或者https://stackoverflow.com/questions/1420839/cant-connect-to-mysql-server-error-111
http://blog.chinaunix.net/uid-20785090-id-3987500.html
可以先试试关闭iptables来排除是否是iptables问题 也可以看看是不是前端MySQL的端口是否是3306
一般这种问题有四个原因:
1,服务器是否真的启动
2,端口是多少.
3,是否有防火墙阻止，可以通过telnet来测试.
4,在OS是否定义了变量MYSQL_TCP_PORT.   
真正的密码或是没有授权，错误应该是"ERROR 1045 (28000): Access denied for user 'root'@'XXX.XXX.XXX.XXX' (using password: YES)"

**Comment by koyomisan** [comment]
谢谢你的回复，其实原因是我把node_id当成节点等级了,不好意思..
